name: Release Actions

on:
    push:
        tags:
            - 'v*.*.*'

permissions:
    contents: write

defaults:
    run:
        shell: bash

jobs:
    build:
        name: Build executable file ${{ github.ref_name }}
        runs-on: windows-latest

        env:
            API_KEY: ${{ secrets.NEOPLE_API_KEY }}

        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: "3.10"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Build EXE file
              run: |
                pyinstaller --onefile --distpath ./dist GetDundam.py
            
            - name: Upload EXE file
              uses: actions/upload-artifact@v4
              with:
                name: GetDundam.exe
                path: dist/GetDundam.exe

    release:
        runs-on: windows-latest
        needs: build

        steps:
            - name: Download EXE file
              uses: actions/download-artifact@v4
              with:
                name: GetDundam.exe

            - name: List downloaded files
              run: ls -R .

            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ github.ref_name }}
                files: |
                    GetDundam.exe
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}